cd D:\LEMOI\Multislice\Spectrum\common.dll
regsvr32 ATLNewGrid.dll
regsvr32 Controls.dll
regsvr32 IFractal.dll
regsvr32 Imctrl.dll
regsvr32 Imfilter.dll
regsvr32 Imksa.dll
regsvr32 Imodel.dll
regsvr32 Imorph.dll
regsvr32 Improc.dll
regsvr32 ImprocEx.dll
regsvr32 Imvpho.dll
regsvr32 ScienceViewer.dll
regsvr32 SFFilter.dll
regsvr32 Wavelets.dll
regsvr32 XVisual.dll