//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Layers32.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_AMPLIFIRE                   106
#define BMP_FORMULA1                    110
#define BMP_FORMULA2                    111
#define BMP_F                           112
#define BMP_Y                           113
#define BMP_a                           114
#define BMP_A1                          115
#define BMP_A2                          116
#define BMP_b                           117
#define BMP_c                           118
#define BMP_FORMULA3                    119
#define BMP_alfa                        120
#define BMP_beta                        121
#define BMP_n                           122
#define BMP_FORMULA4                    123
#define BMP_d                           124
#define BMP_alfa1                       125
#define BMP_alfa2                       126
#define BMP_beta1                       127
#define IDR_MAINFRAME                   128
#define IDR_LAYERSTYPE                  129
#define IDI_ICON1                       130
#define BMP_FORMULA5                    130
#define IDD_PATH                        131
#define IDD_CONSTANTA                   132
#define IDD_WAVE                        133
#define IDD_CHESS                       134
#define IDD_RECT                        135
#define IDD_FORMULA6                    136
#define IDD_CIRCLE                      136
#define IDD_NOISE                       137
#define BMP_beta2                       137
#define IDD_KLIN                        138
#define IDD_FRACTAL                     139
#define IDD_KVAZI                       141
#define IDD_OBOB                        142
#define IDD_ANIZOTROP                   143
#define IDD_TURBO                       144
#define BMP_FORMULA6                    145
#define BMP_FORMULA7                    146
#define IDD_KVAZI2                      148
#define BMP_A3                          149
#define IDD_SP_2_TYPE                   150
#define BMP_FORMULA8                    151
#define BMP_alfa3                       152
#define IDD_DEFOKUS                     153
#define IDD_EXAMPLE                     154
#define IDB_APERTURA                    155
#define IDD_LATDLG_PROGRESS             155
#define IDB_delta                       156
#define IDD_LATDLG_DIALOG               156
#define BMP_FORMULA9                    157
#define IDD_ATOMS                       157
#define IDB_AMNGSTREN                   158
#define IDD_INFO                        159
#define IDD_NAME_L2DB                   160
#define IDC_COUNT                       1000
#define IDC_A1                          1000
#define IDC__A                          1000
#define IDC_FORMULA                     1001
#define IDC_F_A1                        1001
#define IDC__Afi                        1001
#define IDC_APERTURA                    1002
#define IDC_Y_A1                        1002
#define IDC__Agam                       1002
#define IDC_WAVE                        1003
#define IDC_A                           1003
#define IDC_alfa                        1003
#define IDC_LAYERS                      1004
#define IDC_POS                         1004
#define IDC_F_A                         1004
#define IDC_afi                         1004
#define IDC_F_alf1                      1004
#define IDC_UP                          1005
#define IDC_PREDEL                      1005
#define IDC_Y_A                         1005
#define IDC_agam                        1005
#define IDC_Y_alfa1                     1005
#define IDC_FT                          1006
#define IDC_HSCROLLBAR                  1006
#define IDC_MODULAC                     1006
#define IDC_A22                         1006
#define IDC__B                          1006
#define IDC_AT                          1007
#define IDC_F_A22                       1007
#define IDC__Bfi                        1007
#define IDC_APERTURA_PAM                1007
#define IDC_STATIC_CELL                 1007
#define IDC_DEM                         1008
#define IDC_Y_A22                       1008
#define IDC__Bgam                       1008
#define IDC_WAVE_PAM                    1008
#define IDC_B                           1009
#define IDC_AL                          1009
#define IDC__gamma                      1009
#define IDC_LAYERS_PAM                  1009
#define IDC_SPIN                        1010
#define IDC_F_AL                        1010
#define IDC__gfi                        1010
#define IDC_COUNT_PAM                   1010
#define IDC_AMP                         1011
#define IDC_Y_B                         1011
#define IDC_Y_AL                        1011
#define IDC_be2                         1011
#define IDC__ggam                       1011
#define IDC_F_A2_                       1011
#define IDC_MODULAC_PAM                 1011
#define IDC_STATIC_SCALE                1011
#define IDC_PERIOD                      1012
#define IDC_C                           1012
#define IDC_BE                          1012
#define IDC__W                          1012
#define IDC_NAPR_PAM                    1012
#define IDC_DIRECT                      1013
#define IDC_DARK                        1013
#define IDC_DEMRECT                     1013
#define IDC_F_C                         1013
#define IDC_F_BE                        1013
#define IDC__Wfi                        1013
#define IDC_alfa2                       1013
#define IDC_LIGHT                       1014
#define IDC_COUNTRECT                   1014
#define IDC_DIAMETR                     1014
#define IDC_Y_C                         1014
#define IDC_Y_BE                        1014
#define IDC__Wgam                       1014
#define IDC_beta                        1014
#define IDC_FON                         1015
#define IDC_TON                         1015
#define IDC_N                           1015
#define IDC_DEM3                        1015
#define IDC_Y_A2_                       1015
#define IDC_RECT                        1016
#define IDC_INTEN_FON                   1016
#define IDC_MIN                         1016
#define IDC_F_N                         1016
#define IDC_FT3                         1016
#define IDC_F_A3                        1016
#define IDC_EDIT_ATOM_X                 1016
#define IDC_INTEN_CIRCLE                1017
#define IDC_MAX                         1017
#define IDC_Y_N                         1017
#define IDC_AT3                         1017
#define IDC_Y_A3                        1017
#define IDC_EDIT_ATOM_Y                 1017
#define IDC_RADIO2                      1018
#define IDC_KRUT                        1018
#define IDC_H                           1018
#define IDC_DEM2                        1018
#define IDC_SPIN3                       1018
#define IDC_F_a_l                       1018
#define IDC_COMBO_ATOMS                 1018
#define IDC_Y                           1019
#define IDC_X                           1020
#define IDC_ADD_ATOM                    1020
#define IDC_A2                          1021
#define IDC_FT2                         1021
#define IDC_b1                          1021
#define IDC_COMBO_LAYERS                1021
#define IDC_F_A2                        1022
#define IDC_AT2                         1022
#define IDC_c1                          1022
#define IDC_Y_a_l                       1022
#define IDC_Y_A2                        1023
#define IDC_SPIN2                       1023
#define IDC_d1                          1023
#define IDC_F_b_                        1023
#define IDC_ADD_LAYER                   1023
#define IDC_F_B                         1024
#define IDC_al1                         1024
#define IDC_Y_b_                        1024
#define IDC_L2_DEL_LAYER                1024
#define IDC_be1                         1025
#define IDC_F_c_                        1025
#define IDC_L5_LOAD                     1025
#define IDC_al2                         1026
#define IDC_Y_c_                        1026
#define IDC_L5_SAVE                     1026
#define IDC_F_alfa2                     1027
#define IDC_alfa1                       1028
#define IDC_Y_alfa2                     1029
#define IDC_A3                          1030
#define IDC_F_beta                      1031
#define IDC_Y_beta                      1032
#define IDC_TAB                         1032
#define IDC_gamma_                      1034
#define IDC_F_beta__                    1035
#define IDC_Y_beta__                    1036
#define IDC_GUIDE_1                     1036
#define IDC_F_gamma_                    1037
#define IDC_GUIDE_2                     1037
#define IDC_Y_gamma_                    1038
#define IDC_GUIDE_ALL                   1038
#define IDC_A2_                         1039
#define IDC_L1_STATIC_X                 1039
#define IDC_A3_                         1040
#define IDC_L1_STATIC_Y                 1040
#define IDC_alfa1_                      1041
#define IDC_GUIDE_3                     1041
#define IDC_A1_                         1042
#define IDC_L3_STATIC_LATOPT            1042
#define IDC_F_A1__                      1043
#define IDC_L3_STATIC_VIEWAREA          1043
#define IDC_Y_A1__                      1044
#define IDC_L3_X                        1044
#define IDC_alfa2_                      1045
#define IDC_L3_Y                        1045
#define IDC_alfa3_                      1046
#define IDC_L3_DIMENSION                1046
#define IDC_beta_                       1047
#define IDC_L3_STATIC_DIM               1047
#define IDC_C_                          1048
#define IDC_L3_STATIC_Y                 1048
#define IDC_B_                          1049
#define IDC_L3_STATIC_X                 1049
#define IDC_Y_c__                       1050
#define IDC_L3_EXTRA_AREA               1050
#define IDC_F_c__                       1051
#define IDC_L3_STATIC_EXTRA_AREA        1051
#define IDC_F_b__                       1052
#define IDC_L2_EDIT_Z                   1052
#define IDC_F_a__                       1053
#define IDC_L2_STATIC_Z                 1053
#define IDC_F_alfa3__                   1054
#define IDC_GUIDE_4                     1054
#define IDC_F_alfa2__                   1055
#define IDC_L4_STATIC_ATOMOFFS          1055
#define IDC_F_alfa1__                   1056
#define IDC_L4_ATOMOFFS                 1056
#define IDC_F_A3__                      1057
#define IDC_L4_STATIC_CELLOFFS          1057
#define IDC_F_A2__                      1058
#define IDC_L4_CELLOFFS                 1058
#define IDC_Y_A2__                      1059
#define IDC_ALL_EDIT_NUMLAYERS          1059
#define IDC_Y_A3__                      1060
#define IDC_ALL_STATIC_NUMLAYERS        1060
#define IDC_Y_alfa1__                   1061
#define IDC_PROGRESS1                   1061
#define IDC_GUIDE_5                     1061
#define IDC_Y_alfa2__                   1062
#define IDC_Y_alfa3__                   1063
#define IDC_Y_a__                       1064
#define IDC_Y_b__                       1065
#define IDC_D                           1066
#define IDC_CCF                         1067
#define IDC_CXP                         1068
#define IDC_KOS                         1078
#define IDC_PAM                         1079
#define IDC_GRAF                        1079
#define IDC_SIN                         1081
#define IDC_COS                         1082
#define IDC_REDRAW                      1083
#define IDC_SCROLLBAR                   1095
#define IDC_AP_DIAF                     1097
#define IDC_ZNAK_DEF                    1099
#define IDC_AUTO_DEFOC                  1100
#define IDC_STATIC1                     1107
#define IDC_HELP_DEM                    1108
#define IDC_NAME                        1116
#define ID_PROCESSING                   32771
#define ID_CONSTANT                     32772
#define ID_BUTTON32773                  32773
#define ID_WAVE                         32774
#define ID_CHESS                        32775
#define ID_RECT                         32776
#define ID_CIRCLE                       32777
#define ID_NOISE                        32778
#define ID_KLIN                         32779
#define ID_BUTTON32780                  32780
#define ID_FRACTAL                      32781
#define ID_SAVE_SPECTR_SP               32782
#define ID_SAVE_SPECTR_BMP              32783
#define ID_COEFF_S                      32784
#define ID_BUTTON32785                  32785
#define ID_KVAZI                        32786
#define ID_BUTTON32787                  32787
#define ID_OBOB                         32788
#define ID_BUTTON32789                  32789
#define ID_ANIZOTROP                    32790
#define ID_TURBO                        32791
#define ID_BUTTON32792                  32792
#define ID_EXAMPLE                      32793
#define IDS_TAB_TIP_1                   32794
#define ID_KVAZI2                       32795
#define ID_BUTTON32796                  32796
#define ID_SP2TYPE                      32797
#define ID_CERNIC                       32798
#define IDS_TAB_TIP_2                   32799
#define ID_DEFOKUS                      32800
#define IDS_TAB_TIP_3                   32801
#define ID_START                        32802
#define ID_BUTTON32803                  32803
#define ID_ABER                         32804
#define IDS_TAB_TIP_4                   32805
#define IDS_TAB_TIP_5                   32806
#define ID_ATOMS                        32807
#define ID_SHOW_WIN                     32808
#define IDS_TAB_TIP_6                   32809
#define ID_L2DB                         32809
#define IDS_TAB_TIP_7                   32810
#define IDS_TAB_TIP_8                   32811

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
